version: '3.8'
services:
  db:
    image: postgres:16.3
    container_name: hospital-system-db
    environment:
      POSTGRES_DB: hospital-system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: en_US.UTF-8
      LC_MESSAGES: en_US.UTF-8
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./dumps:/docker-entrypoint-initdb.d
volumes:
  pgdata:
#  docker exec -it legacy-hospital-system-db psql -U postgres -d legacy-hospital-system -c "\dt"
